### ISSUE TITLE
The One Large Deployment Diagram

### ISSUE THREAD

**Issue by Regan-Koopmans** [wanrick/COS301-TeamNature#18]
For the document we need single architectural diagram that shows all 11 modules (including ones that we have not picked), and their relationships to one another.

Unless we use an online collaborative UML drawing tool, I suspect it will be difficult to collaborate on this task. Therefore I believe one, maybe two, people should take this task upon themselves, and this can be their major contribution to the final document.

**Comment by SiyaSNazo** [comment]
[MagicDraw Deployment.pdf](https://github.com/wanrick/COS301-TeamNature/files/836504/MagicDraw.Deployment.pdf)

[MagicDraw Deployment.pdf](https://github.com/wanrick/COS301-TeamNature/files/836506/MagicDraw.Deployment.pdf)
